### ISSUE TITLE
Error: "Unable to connect to the Gecko profiler add-on within five seconds."

### ISSUE THREAD

**Issue by mikeconley** [firefox-devtools/Gecko-Profiler-Addon#64] opened 2017-05-09 20:08 UTC
Originally filed at https://github.com/bgirard/Gecko-Profiler-Addon/issues/115, and quoting mostly verbatim.

Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

I'm using Gecko Profile 0.8, from today, May 9th.

Invoking a profile capture, I just got:

![6b0c7f7a-34ad-11e7-881b-9286764f50ce](https://cloud.githubusercontent.com/assets/195042/25870251/723fe4f2-34d1-11e7-806a-ce99ee005d3c.png)

Stack:

    Error: Unable to connect to the Gecko profiler add-on within five seconds.
    Stack trace: e/</<@https://perf-html.io/9170dacdedc70ab6d307.bundle.js:30:6819 9170dacdedc70ab6d307.bundle.js:33:6467
    Unhandled promise rejection Error: Unable to connect to the Gecko profiler add-on within five seconds.
    Stack trace:
    e/</<@https://perf-html.io/9170dacdedc70ab6d307.bundle.js:30:6819 9170dacdedc70ab6d307.bundle.js:35:46
    Successfully compiled asm.js code (loaded from cache in 9169ms)
    zee-worker.js

**Comment by mstange** [comment] 2017-05-09 20:13
Thanks.

I just landed a workaround for this in https://github.com/devtools-html/perf.html/pull/312 but I think this is also a problem on the add-on side.
I think this is happening because it takes longer than 5 seconds for the profile to arrive at the content process, due to the [expensive structured cloning](https://bugzilla.mozilla.org/show_bug.cgi?id=1362792) that's currently happening in the parent process. But our content script should be trying to connect to the page as soon as it can, without waiting for the profile.

**Comment by mikeconley** [comment] 2017-05-09 21:08
I _believe_ you can side-step the structured clone problem if you stringify the profile first before sending it through. Last I heard, sad as it is, this was faster than structured clone.

**Comment by mstange** [comment] 2017-05-09 21:18
Yes, we can side-step it. I'd prefer [an array buffer](https://bugzilla.mozilla.org/show_bug.cgi?id=1362800) over a string, though.

**Comment by mirh** [comment] 2018-06-04 22:36
Stupid discovery of the day: I couldn't really really get the profile to load after "capture". 
Even after minutes for 10 seconds of recording. 
And since quite some months by now. 

I toggled off some of the default features checkboxes.. I lowered resolution and buffer size.. 
I pressed "apply" (rather than start) and it worked. :\
Not to mention that when I put everything back to *vanilla*.. It still continued to work even then

**Comment by gregtatum** [comment] 2020-03-27 18:15
Not sure there is anything actionable here. This infrastructure has changed a bit in the last few months. If there are any new issues please re-file with steps to reproduce here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Performance+Tools+%28Profiler%2FTimeline%29

**Closed as completed by gregtatum** 2020-03-27 18:15 UTC
