### ISSUE TITLE
Enable resizing worker names list and worker timelines vs call stacks view

### ISSUE THREAD

**Issue by juj** [firefox-devtools/Gecko-Profiler-Addon#92] opened 2017-08-24 07:11 UTC
Profiling application with 20+ web workers that do various tasks in a 3D game engine, there are two spots on the UI that would be super useful to be resizable. See the following image for an illustration.

<img width="882" alt="screenshot from 2017-08-24 10-01-09" src="https://user-images.githubusercontent.com/225351/29653870-db6950c2-88b3-11e7-887d-ef1ef634d326.png">

The first one on the top left delimits Worker names from the swimlanes. The text is cut off, but it's not possible to scroll to see the full text, or resize the column delimiter manually to expand the full text to be visible. Mouse hovering on top of the text "DOM Worker 'pthread-...' does not show a tooltip that would show the full text either. It would help to be able to resize that column.

The second one is the horizontal line that separates the Worker swimlanes from the call stack tree view. I would be nice to be able to sometimes expand the top bar to be large to get a high level view of all threads in the system, whereas other times, it'd be helpful to expand the view on the call stack tree hierarchy instead, so being able to resize these would allow achieving that.

**Comment by gregtatum** [comment] 2017-08-24 14:37
I didn't think about the thread names area, that would be nice as well. This is a duplicate of https://github.com/devtools-html/perf.html/issues/67. I copied your message in that issue, and I am closing this one in favor of the other. Thanks for the feedback!

**Closed as completed by gregtatum** 2017-08-24 14:37 UTC
